name: CI-Test-On-Branch-And-Tag

on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  tag-commit:
    runs-on: ubuntu-latest
    needs: test
    permissions: write-all
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.6
    
      - name: Generate Build Number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prefix: ""
    
      - name: Create Git Tag
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${process.env.BUILD_NUMBER}`,
              sha: context.sha
            })
        env:
          BUILD_NUMBER: ${{ steps.buildnumber.outputs.build_number }}